publishers:

  obstacle_boxes:
    topic: /obs_map
    queue_size: 4
    frame_id: camera

  bounding_boxes:
    topic: /cubicle_detection/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /cubicle_detection/detection_image
    queue_size: 1
    latch: true

  disparity_map:
    topic: /disparity_map
    frame_id: camera
    queue_size: 10

  obs_disparity_map:
    topic: /obs_disparity_map
    frame_id: camera
    queue_size: 10

image_view:

  enable_opencv: true
  wait_key_delay: 2
  enable_console_output: true
  eval: false
